# install.packages("devtools")
# devtools::install_github("hadley/devtools")
detach("package:wastdr", unload=TRUE)
devtools::install_github("parksandwildlife/wastdr", force=TRUE)
library(wastdr)
tnejson <- get_wastd('turtle-nest-encounters')
tne <- parse_turtle_nest_encounters(tnejson)
aejson <- get_wastd('animal-encounters')
ae <- parse_animal_encounters(aejson)