---
title: "Test workbook"
author: "Kesia"
date: "`r Sys.time()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(wastdr)
wastdr_setup(
  api_url = Sys.getenv("WASTD_API_URL"), 
  api_token = Sys.getenv("WASTD_API_TOKEN"))
```
## Downloading data
```{r download_data, eval=F}

if (file.exists("data/tnejson.Rda")){
  load("data/tnejson.Rda")
} else {
  tnejson <- wastdr::get_wastd(
    'turtle-nest-encounters', 
    query = list(taxon = "Cheloniidae", 
                 format = "json",
                 area=17))
  save(tnejson, file = "data/tnejson.Rda")
}

tne <- parse_turtle_nest_encounters(tnejson)

if (file.exists("data/aejson.Rda")){
  load("data/aejson.Rda")
} else {
  aejson <- wastdr::get_wastd(
    'animal-encounters', 
    query = list(taxon = "Cheloniidae", 
                 format = "json",
                 area=17))
  save(aejson, file = "data/aejson.Rda")
}
ae <- parse_animal_encounters(aejson)

save.image("data/data.RData")
```

## Data
Raw data contains all observations:
```{r resume_from_saved_data}
load("~/Projects/turtles/data/data.RData")
```

```{r show_json}
# listviewer::jsonedit(aejson$features)
# listviewer::jsonedit(tnejson$features)
```

Parsed data is tabular:
```{r show_dt}
DT::datatable(head(ae, n = 100))
DT::datatable(head(tne, n = 100))
```

## Further reading

* [Example workbook](http://rpubs.com/florian_mayer/tracks)
* [wastdr homepage](https://parksandwildlife.github.io/wastdr/)
